### ISSUE TITLE
Support Validating the Ingress Object via an Admission Webhook

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#117]
**What**

To enforce our default policy of no custom domains, we allow the custom domain to be added and then remove it from the Ingress object.  Now that KCP allows admission [webhooks](https://github.com/kcp-dev/kcp/issues/143), we should improve the user experience by adding a validating webhook that rejects the Ingress if it has a custom host with a user friendly response.
The webhook will need to be exposed on a publicly accessible host, we can use GLBC to configure its own host. The webhook wiill need to be configured per workspace

```
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "response": {
    "uid": "<value from request.uid>",
    "allowed": false,
    "status": {
      "code": 400,
      "message": "Custom domains are not currently supported. Host should be blank"
    }
  }
}
```

- [ ] Suggestion: Create a separate binary and container for the webhook
- [ ] Investigate Auth options (esp as this will be exposed via a public host) can we verify using workspace api server cert?
- [ ] Implement the validating webhook 
- [ ] update our deployment to also create a service and ingress to this webhook
- [ ] update/add e2e test that test the webhook functionality

**Comment by maleck13** [comment]
We can acheive this with the concept of transformations. No need for webhook for ingress objects
