### ISSUE TITLE
Support deploying GLBC via a KCP instance

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#94]
**What**

Rather than deploying directly to a cluster, we should support deploying the GLBC and its components through KCP.

This will mean creating a workspace, workloadcluster, service account, clusterrole clusterrole binding and the deployment for GLBC via KCP, this also has to include cert-manager. We will need to create CRDs in our workspace that are needed by cert-manager. This should target our own pcluster

- [x] #161
- [ ] Add a doc that explains how to do this (IE setting up a workspace, workloadcluster, resources to sync etc)
- [x] Investigate connecting cert-manager to our workspace directly
- [x] create data flow diagrams
Open Question
Should we update our e2e tests to work this way also?

**Comment by maleck13** [comment]
As part of this we should also look at connecting cert-manager back to our service workspace and see can we just create certificates in our own workspace

**Comment by maleck13** [comment]
@mikenairn @astefanutti I think we should look at this before taking on the refactor of cert management. This is because if we can connect cert-manager back to our service workspace we can create probably create the certificates in our own workspace and so not need to communicate with the local pcluster API

**Comment by astefanutti** [comment]
Right, I agree this would be better we settle on the deployment model ASAP, as this ripples in lots of areas. AFAIK, transparent deployment via KCP is only supported for the default service account. I'm not sure how important that limitation is, for sure something to clarify during this investigation...

As for the refactoring of TLS certificate management, I'd be inclined to think it should not have a strong dependency on this. One of the outcome of that refactoring should ideally be that it should make the certificate issuance logic as orthogonal to the deployment model as possible, i.e., switching from one mode to another should be made as seamless as possible. But that would be the theory :)

**Comment by maleck13** [comment]
Sure I agree also actually, what you say makese sense the difference is the client being used to target a kube API server

**Comment by mikenairn** [comment]
> Add a doc that explains how to do this (IE setting up a workspace, workloadcluster, resources to sync etc)

Additional documentation will be added as part of the upgrade to KCP 0.5.0 https://github.com/Kuadrant/kcp-glbc/issues/197. 

> Investigate connecting cert-manager to our workspace directly

Cert manager is deployed via KCP also and APIExports/APIBindings used

> create data flow diagrams

A diagram was created as part of the proposal doc https://github.com/Kuadrant/kcp-glbc/blob/main/docs/proposals/deployment_via_kcp.md#architecture

> Open Question
> Should we update our e2e tests to work this way also?

Where possible, the e2e tests will be updated to use the same setup as a deployment of glbc as part of https://github.com/Kuadrant/kcp-glbc/issues/197
